$schema: "http://json-schema.org/draft-07/schema#"
description: entries for the sample sheet
properties:
  sample_name:
    type: string
    description: sample name/identifier
  group:
    type: string
    description: grouping of samples (for example per patient)
  alias:
    type: string
    description: type of sample within a group (for example tumor, normal)

required:
  - sample_name
  - group
  - alias
